version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  publisher:
    build:
      context: .
      dockerfile: publisher/Dockerfile
    volumes:
      - ./publisher:/app
    depends_on:
      - mqtt-broker

  subscriber:
    build:
      context: .
      dockerfile: subscriber/Dockerfile
    volumes:
      - ./subscriber:/app
    depends_on:
      - mqtt-broker
