version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  publisher:
    build:
      context: ./publisher
    depends_on:
      - mqtt-broker

  subscriber:
    build:
      context: ./subscriber
    depends_on:
      - mqtt-broker

  mcp-server:
    build:
      context: ./mcp_server
    ports:
      - "8000:8000"
    depends_on:
      - mqtt-broker
